### ISSUE TITLE
Fixed duration of election

### ISSUE THREAD

**Issue by sahil-ramagiri** [WebdevteamIG/blockchainvoting#21]
Pass duration of election in constructor and no votes should count after the duration.

**Comment by saitejach127** [comment]
Convert the code into fixed duration at the time of constructor instead of manually ending the election but keep the manually ending for safe side
Features:
Pass duration in constructor
End election in that duration
Able to end election in between by only admin

**Comment by sahil-ramagiri** [comment]
Can I work on this

**Comment by saitejach127** [comment]
Sure go ahead
