### ISSUE TITLE
Fixed candidates

### ISSUE THREAD

**Issue by sahil-ramagiri** [WebdevteamIG/blockchainvoting#22]
Candidates are fixed at the time of construction.

**Comment by saitejach127** [comment]
Add candidates at time of deployment instead of dynamic adding.
Features:
Pass candidates in the constructor
Assign candidates in constructor
Remove existing addCandidate function

**Comment by dheerajd5** [comment]
Can you assign this issue to me?

**Comment by saitejach127** [comment]
Sure go ahead
