### ISSUE TITLE
Adding Candidate

### ISSUE THREAD

**Issue by saitejach127** [WebdevteamIG/blockchainvoting#4]
Complete add candidate function by adding the new candidate to candidates array and verify  not duplicates exist in it

**Comment by hvardhan2000** [comment]
assign me this

**Comment by hvardhan2000** [comment]
can u look into my pr?

**Comment by saitejach127** [comment]
You are using another memory for checking if user exists. Can you do without it because in ethereum storage will cost more money that's why. You can compromise on the time efficiency
